server:
  port: 8081


spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/accountDB
    username: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:greethy@123}
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2000
      password: ${REDIS_PASSWORD:greethy@123}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    url: jdbc:mysql://localhost:3306/accountDB
    user: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:greethy@123}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDP_ISSUER_URI:http://localhost:8180/realms/greethy}
          jwk-set-uri: ${IDP_JWK_SET_URI:http://localhost:8180/realms/greethy/protocol/openid-connect/certs}

#keycloak:
#  client-id:
#  client-secret:
